# Generated by Django 5.0.6 on 2024-06-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malewa', '0002_boisson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boisson',
            name='priceL',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='boisson',
            name='priceM',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='plat',
            name='priceL',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='plat',
            name='priceM',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
